### ISSUE TITLE
Quickly viewing Filenames

### ISSUE THREAD

**Issue by FFA2016** [BuildTheEarth/terraplusplus#3]
**Is your feature request related to a problem? Please describe.**
So i don't know, if it's to 100% right for this Mod, but we always have the issue, that we first have to go to the website, search for the right chunk on the map and calculate the .3dr filenames... That is just too much effort for finding 1 chunk in my oppinoin

**Describe the solution you'd like**
Maybe you could implement a command, that gives someone the Filename for the Chunks the Player is currently standing in

**Describe alternatives you've considered**

**Comment by rudeyeti** [comment]
I could definitely make that a feature in a few hours, if you want. It would probably more align with the CubicChunks Mod rather than TerraPlusPlus, but it's probably easier to add it in here. I'll do some testing and then add it in.

**Comment by SmylerMC** [comment]
Terramap can do that already, see the first screenshot on the [CurseForge](https://www.curseforge.com/minecraft/mc-mods/terramap) or [Github](https://github.com/SmylerMC/terramap) page. 
I'm not sure if it's really necessary to have it in terra++, since it's not really related to world gen. If we would have it as a command or something we should probably make a PR to cubic chunks.

**Comment by rudeyeti** [comment]
That actually would probably be the best using TerraMap, but if you really want it as an in-game command then we should add it into CubicChunks like Smyler was saying.

**Comment by FFA2016** [comment]
Ok thank you
