### ISSUE TITLE
Mod for Bukkit (spigotmc, ...)

### ISSUE THREAD

**Issue by debian-user-france1** [BuildTheEarth/terraplusplus#40]
**Is your feature request related to a problem? Please describe.**
I don't wanna force the players to install forge+mod and I could add a terraplusplus to my spigotmc server maybe if there is a Plugin. It makes no sense doing a mod because hosting the world is Server sided and the /terra command usw can be integrated in a Plugin so I do not see any reason to make mods (except compatibilities).

**Describe the solution you'd like**
A plugin that runs the mod inside a bukkit Server?

**Describe alternatives you've considered**
Well I tried to do another Server with forge but failed due to old Minecraft (Not Java 16 compatible?)

**Comment by Coppertine** [comment]
First off, if you are looking to intergrate terraplusplus into a spigotmc instance. I'd suggest using Mohist, although it isn't the most sable, it's the only one we can use. Secondly, it's best to enable the Vanilla Client in the Cubic Chunks config file so that anyone in 1.12.2 without the mod can join.

**Comment by DaMatrix** [comment]
no, not happening. there would be no reason to do this, because vanilla height limits would make it pointless.

if you want to allow unmodded clients to join, your best bet is (as Coppertine already mentioned) to enable vanilla client support in Cubic Chunks' config.
